### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by GreatGoatHead** [farsider350/p2pool-dgb-scrypt-350#6]
It seems the DGB scrypt P2Pool is not working with antminers. The server seems to work but the miners are not connecting and not hashing. I know you are busy but could you point me in the correct direction to resolving this issue? I would be happy to research more and test but you had the best working model so I wanted to ask you..  Thanks.

**Comment by frstrtr** [comment]
L3+ works fine

**Comment by farsider350** [comment]
It should be working fine. I'm still using this repo with Antminers
